server:
  port: 8080

spring:
  application:
    name: proxy-api-example

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: event-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/event/**